# coding: utf-8

import urlparse
from django.conf import settings

BASE_URL = urlparse.urljoin(settings.STATIC_URL, 'fileicons/img')
DEFAULT_ICON = 'txt.png'
TEMPLATE_IMAGE_TAG = getattr(settings,
                             'FILEICON_TEMPLATE_IMAGE_TAG',
                             '<img src="%(url)s" width="16" height="16" class="fileicons">')
ICON_LIST = {
    '7z': '7z.png',
    'aiff': 'aiff.png',
    'ai': 'ai.png',
    'asc': 'asc.png',
    'audio': 'audio.png',
    'bin': 'bin.png',
    'bz2': 'bz2.png',
    'cfc': 'cfc.png',
    'cfm': 'cfm.png',
    'chm': 'chm.png',
    'class': 'class.png',
    'conf': 'conf.png',
    'c': 'c.png',
    'cpp': 'cpp.png',
    'cs': 'cs.png',
    'css': 'css.png',
    'csv': 'csv.png',
    'deb': 'deb.png',
    'divx': 'divx.png',
    'doc': 'doc.png',
    'docx': 'doc.png',
    'dot': 'dot.png',
    'eml': 'eml.png',
    'enc': 'enc.png',
    'file': 'file.png',
    'gif': 'gif.png',
    'gz': 'gz.png',
    'hlp': 'hlp.png',
    'html': 'html.png',
    'htm': 'htm.png',
    'image': 'image.png',
    'iso': 'iso.png',
    'jar': 'jar.png',
    'java': 'java.png',
    'jpeg': 'jpeg.png',
    'jpg': 'jpg.png',
    'js': 'js.png',
    'lua': 'lua.png',
    'mm': 'mm.png',
    'mov': 'mov.png',
    'mp3': 'mp3.png',
    'mpg': 'mpg.png',
    'm': 'm.png',
    'odc': 'odc.png',
    'odf': 'odf.png',
    'odg': 'odg.png',
    'odi': 'odi.png',
    'odp': 'odp.png',
    'ods': 'ods.png',
    'odt': 'odt.png',
    'ogg': 'ogg.png',
    'pdf': 'pdf.png',
    'pgp': 'pgp.png',
    'php': 'php.png',
    'pl': 'pl.png',
    'png': 'png.png',
    'ppt': 'ppt.png',
    'pptx': 'ppt.png',
    'ps': 'ps.png',
    'py': 'py.png',
    'ram': 'ram.png',
    'rar': 'rar.png',
    'rb': 'rb.png',
    'rm': 'rm.png',
    'rpm': 'rpm.png',
    'rtf': 'rtf.png',
    'sig': 'sig.png',
    'sql': 'sql.png',
    'swf': 'swf.png',
    'sxc': 'sxc.png',
    'sxd': 'sxd.png',
    'sxi': 'sxi.png',
    'sxw': 'sxw.png',
    'tar': 'tar.png',
    'tex': 'tex.png',
    'tgz': 'tgz.png',
    'txt': 'txt.png',
    'vcf': 'vcf.png',
    'video': 'video.png',
    'vsd': 'vsd.png',
    'wav': 'wav.png',
    'wma': 'wma.png',
    'wmv': 'wmv.png',
    'xls': 'xls.png',
    'xlsx': 'xls.png',
    'xml': 'xml.png',
    'xpi': 'xpi.png',
    'xvid': 'xvid.png',
    'zip': 'zip.png',
}